apiVersion: v1
kind: Service
metadata:
  name: bookshop-config-service
  labels:
    app: bookshop-config-service
spec:
  type: ClusterIP
  selector:
    app: bookshop-config-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888